name: CI
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 9.4.0
      - run: npm install --legacy-peer-deps
      - run: npm run nx build crew --verbose